package Cobain;

import java.awt.Image;
import java.awt.Toolkit;
import whack_a_mole.Audio;

/**
 *
 * @author Vivobook
 */
public class coba1 extends javax.swing.JFrame {

    private String filename;
    /**
     * Creates new form coba2
     */
    public coba1() {
        initComponents();
        this.setTitle("Game Dino");
        this.setVisible(false);
        this.setResizable(false);
        Image icon = Toolkit.getDefaultToolkit().getImage("src/Cobain/dino-awal.png");
        setIconImage(icon);
        Audio backgroundMusic = new Audio("src\\res\\start.wav");
        backgroundMusic.play();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        start = new javax.swing.JButton();
        textawal = new javax.swing.JLabel();
        dinoawal = new javax.swing.JLabel();
        background = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 255, 102));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setFocusableWindowState(false);

        jPanel1.setForeground(new java.awt.Color(255, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        start.setBackground(new java.awt.Color(255, 255, 153));
        start.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        start.setForeground(new java.awt.Color(51, 102, 0));
        start.setText("START");
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });
        jPanel1.add(start, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 160, 50));

        textawal.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        textawal.setForeground(new java.awt.Color(102, 153, 0));
        textawal.setText("GAME DINO");
        jPanel1.add(textawal, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        dinoawal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cobain/dino-awal.png"))); // NOI18N
        dinoawal.setText("jLabel2");
        jPanel1.add(dinoawal, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 50, 460, 370));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cobain/bg-tanah_1.jpg"))); // NOI18N
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 436, 420));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 430, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed

        coba2 cobain1 = new coba2();
        cobain1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_startActionPerformed

    public static void main(String args[]) {
        //</editor-fold>
        //</editor-        //</editor-fold>
        //</editor-fold>fold>

    /**
     *
     */
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable(){         
                @Override
                public void run() {
                new coba1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel dinoawal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton start;
    private javax.swing.JLabel textawal;
    // End of variables declaration//GEN-END:variables

    
}
